### ISSUE TITLE
Cannot import search

### ISSUE THREAD

**Issue by gandalf012** [renatoviolin/Question-Answering-Albert-Electra#1]
Import trying to import search from googlesearch

Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from googlesearch import search
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'search' from 'googlesearch' (/Users/southpigalle/miniconda3/lib/python3.7/site-packages/googlesearch/__init__.py)
>>> 

Even after pip install googlesearch it's still doesn't work

**Comment by renatoviolin** [comment]
Hi, 
sorry for not include requeriments.txt. I'm preparing it.

To install google search: pip install google

**Comment by gandalf012** [comment]
Thanks. It works

I will wait for your requirements file to continue running your pipeline
