### ISSUE TITLE
No vocab.txt in model

### ISSUE THREAD

**Issue by gandalf012** [renatoviolin/Question-Answering-Albert-Electra#3]
No model/vocab.txt
I suggest you to clone your repo out of initial directory, run it to make sure  that everything is okay

**Comment by renatoviolin** [comment]
The vocab.txt is in the download file together the pre-trained checkpoint.
Make sure to extract and get the following structure:
```
electra_large_qa_model
    data
    model
        model.ckpt-64000
        vocab.txt
    tfrecords
```
Make sure to adjust the DATA_MODEL_DIR to electra_large_qa_model folder.
